# 淘宝/天猫比价规则
# https://cdn.jsdelivr.net/gh/Husky985211/taobao@main/taobao_price_rules.conf

^https?://acs\.m\.taobao\.com/h5/mtop\.taobao\.detail\.getdetail url script-response-body https://cdn.jsdelivr.net/gh/Husky985211/taobao@main/taobao_price.js
^https?://acs\.m\.taobao\.com/h5/mtop\.alibaba\.detail\.getdetail2 url script-response-body https://cdn.jsdelivr.net/gh/Husky985211/taobao@main/taobao_price.js
^https?://detail\.tmall\.com/item\.htm url script-response-body https://cdn.jsdelivr.net/gh/Husky985211/taobao@main/taobao_price.js
^https?://item\.taobao\.com/item\.htm url script-response-body https://cdn.jsdelivr.net/gh/Husky985211/taobao@main/taobao_price.js

hostname = acs.m.taobao.com, detail.tmall.com, item.taobao.com, www.manmanbuy.com
